### ISSUE TITLE
Potential problems with BeamSampler    in  src/evaluate/sampler.py

### ISSUE THREAD

**Issue by newllqllz** [atcbosselut/comet-commonsense#1]
It seems that the beam sampler is doing sth weird when computing losses: (the following line) in  src/evaluate/sampler.py

beam_lls, top_beam_idxs = (hyp_beam_lls / temp_counts).topk(self.opt.eval.bs)

in the loop,  temp_counts is being divided again and again, making the losses for tokens in the begining less and less important.

**Comment by atcbosselut** [comment]
Thanks for pointing this out. I updated `sampler.py` and added a note in the README!
