### ISSUE TITLE
python2 or python3 ?

### ISSUE THREAD

**Issue by 1160300603** [atcbosselut/comet-commonsense#10]
you said that you assumed I have python 3.6, but why do you use python2 style like this???
comet-commonsense/scripts/classify/demo_bilinear.py
line 21            print 'can not find corresponding vector total:', array[0].lower()

**Comment by atcbosselut** [comment]
That's from an outside script copied from: https://ttic.uchicago.edu/~kgimpel/commonsense.html

I added a direct reference to that script in a later UPDATE, but forgot to update the README. Thanks for bringing it to my attention. I'll change the README to reflect that.
