### ISSUE TITLE
Could you please recover the full sentence of this picture? Thank you!

### ISSUE THREAD

**Issue by guotong1988** [atcbosselut/comet-commonsense#14]
<img width="492" alt="WX20191209-194740@2x" src="https://user-images.githubusercontent.com/4702353/70433829-a1910b80-1abd-11ea-9dca-617315a52a83.png">

I am confused about the alignment.

**Comment by atcbosselut** [comment]
Are you asking for the the tokens that make up s, r, and o for the input here?

**Comment by guotong1988** [comment]
Yes. The full input and output.

**Comment by atcbosselut** [comment]
I think it was a made up example that probably looked something like:

PersonX sails... <xNeed> have a sail boat

**Comment by guotong1988** [comment]
What is the output?

**Comment by guotong1988** [comment]
Why the first two tokens of output are two [MASK]?

**Comment by atcbosselut** [comment]
Because during training, we don't learn to predict the tokens of s and r. Our model learns to predict the tokens of o given s and r, so we mask the tokens of s and r at the output during training.

**Comment by guotong1988** [comment]
Thank you very much!
