### ISSUE TITLE
What does Top-N random sampling mean?

### ISSUE THREAD

**Issue by guotong1988** [atcbosselut/comet-commonsense#15]
![image](https://user-images.githubusercontent.com/4702353/70488530-ea83a700-1b33-11ea-9bc7-fb782be06667.png)

I am confused about how to sample. I know what beam search is.
Thank you.

**Comment by atcbosselut** [comment]
https://arxiv.org/pdf/1805.04833.pdf explains it pretty well

**Comment by guotong1988** [comment]
Thank you again.
