### ISSUE TITLE
Is it possible to limit the vocabulary set of generation?

### ISSUE THREAD

**Issue by ehsan-soe** [atcbosselut/comet-commonsense#18]
Hi,

I wonder if it is possible to use the trained comet model, however limit the vocabulary set of generation? In other words have a customized subset of the current vocabulary set and force the model to only generate from that?
I need this specifically for one of the nine available dimensions.

Thanks in advance,

**Comment by atcbosselut** [comment]
If you have a whitelist of words, you can find their index in the vocabulary using the TextEncoder instant object (named `text_encoder` here).

For argmax decoding:

```
whitelist_words = ["$WORD_1", $WORD_2", ...]
whitelist_indices = torch.LongTensor(text_encoder.encode(words)).squeeze(1)

contrained_lm_probs = lm_probs[:, -1, :].index_select(-1, whitelist_indices)
values, indices = contrained_lm_probs.max(dim=-1)

new_idx = whitelist_indices.index_select(0, indices)
```
