### ISSUE TITLE
A question regarding the model selection

### ISSUE THREAD

**Issue by colinzhaoust** [atcbosselut/comet-commonsense#2]
Dear authors,

Thanks for the great work. I just have one small question about your paper. How is the model selected, especially for the conceptnet task? It is selected based on its performance on the dev set or you simply selected the final model after training? 

Thank you so much for your help in advance.

**Comment by atcbosselut** [comment]
The last model that is checkpointed should be the one that achieves the lowest loss on the development set (or subset for ATOMIC). That's the model we select for further analysis.
