### ISSUE TITLE
dear sir, i want to get pre-train model

### ISSUE THREAD

**Issue by Igoslow** [atcbosselut/comet-commonsense#22]
i use this command with bash scripts/setup/get_model_files.sh, but the project seems to be stalled  when gitting clone 36% of this files

**Comment by Igoslow** [comment]
dear sir,
this website https://drive.google.com/file/d/1FccEsYPUHnjzmX-Y5vjCBeyRt1pLo8FB/view  in your Trash can，please check it out thanks

**Comment by Swati17293** [comment]
Its still in the trash.. Please pull it out..

**Comment by Igoslow** [comment]
Thank you very much

**Comment by Igoslow** [comment]
I am following your work, and have started all command line. Thank you very much

**Comment by Igoslow** [comment]
I am following your work, and have achieved all command line. Thank you very much

**Comment by Swati17293** [comment]
> I am following your work, and have achieved all command line. Thank you very much

Hey, If you have the pretrained models. Kindly share please..

**Comment by kaihuchen** [comment]
I also found that  https://drive.google.com/open?id=1FccEsYPUHnjzmX-Y5vjCBeyRt1pLo8FB (for pretrained_models.tar.gz) leads to a message indicating "File is in owner's trash." Wonder if this file can be made accessible again? Thanks in advance!

**Comment by atcbosselut** [comment]
Fixed. Thanks for pointing it out.

**Comment by kaihuchen** [comment]
@atcbosselut  Much appreciated for the speedy response!
