### ISSUE TITLE
get_conceptnet_data.sh gives access denied error

### ISSUE THREAD

**Issue by balkamm** [atcbosselut/comet-commonsense#23]
I'm following the setup instructions but get_conceptnet_data.sh is returning errors:

bash scripts/setup/get_conceptnet_data.sh
--2020-05-17 11:44:00--  https://ttic.uchicago.edu/~kgimpel/comsense_resources/train100k.txt.gz
Resolving ttic.uchicago.edu (ttic.uchicago.edu)... 128.135.8.186
Connecting to ttic.uchicago.edu (ttic.uchicago.edu)|128.135.8.186|:443... connected.
OpenSSL: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
Unable to establish SSL connection.
...

Visiting https://ttic.uchicago.edu/~kgimpel/comsense_resources/ also gives a 403 access forbidden error.

**Comment by atcbosselut** [comment]
It seems to work for me when I run the script, but I can look into hosting the data myself.
