### ISSUE TITLE
Different inference resullt

### ISSUE THREAD

**Issue by xwwwwww** [atcbosselut/comet-commonsense#29]
Hi,
I've tested a number of cases either using code&&parameter from this repo or demo from https://mosaickg.apps.allenai.org/comet_atomic. And I'm kind of confused as there have obvious differences in the results. So what's the exact difference between them?
Thanks

**Comment by atcbosselut** [comment]
Are you using a pretrained model or retraining a model using the code?

Which decoder are you using to decode sequences?
