### ISSUE TITLE
Environment install problems

### ISSUE THREAD

**Issue by sawyermade** [atcbosselut/comet-commonsense#32]
In the README.md you need to change the tensorflow and spacy install methods. pip tensorflow downloads a different version than what is needed and works better if you just use conda to install it. Also, the spacy 3.0 that is default install now, doesn't work with your dataloader. Proposed changes:

pip install tensorflow --> conda install tensorflow
conda install -c conda-forge spacy --> conda install -c conda-forge spacy=2.3.5

**Comment by shaoniana1997** [comment]
can you tell me what is your tensorflow version ?Because i came across a [problem](https://github.com/atcbosselut/comet-commonsense/issues/34#issue-938083471) ,and i guess prehaps it is the problem of tensorflow version

**Comment by atcbosselut** [comment]
Updated README and merged a pull request to make spacy 3.0.0 compatible. Let me know if there's any more issues.
