### ISSUE TITLE
How to generate xIntent output file for a given input file in atomic_single_example.py

### ISSUE THREAD

**Issue by knarfamlap** [atcbosselut/comet-commonsense#35]
Hello!

Thank you for sharing your work! I want to generate xIntent for some sequences. Is there a way that I can give an input file and have the output be stored in another file? 

Thanks for your time!

Frank

**Comment by atcbosselut** [comment]
Yes, you can simply modify https://github.com/atcbosselut/comet-commonsense/blob/master/scripts/interactive/atomic_single_example.py

You should be able to just replace the reading from stdin as a file with the events of interest. And just set the `category` variable to "xIntent"
