### ISSUE TITLE
question about the runtime error

### ISSUE THREAD

**Issue by shaoniana1997** [atcbosselut/comet-commonsense#36]
Here is the detail of the question :
File "comet-commonsense/src/interactive/functions.py", line 124, in get_atomic_sequence
    input_event, category, data_loader, text_encoder)
  File "comet-commonsense/src/interactive/functions.py", line 158, in set_atomic_inputs
    XMB[:, :len(prefix)] = torch.LongTensor(prefix)
RuntimeError: The expanded size of the tensor (18) must match the existing size (93) at non-singleton dimension 1.  Tar         get sizes: [1, 18].  Tensor sizes: [93]
do you know how to deal with it ? @madaan

**Comment by atcbosselut** [comment]
Your input events are too long. The maximum length of the input event can only be 17 tokens.
