### ISSUE TITLE
Can save  model into h5 file or other language model file

### ISSUE THREAD

**Issue by RyanYip-Kat** [atcbosselut/comet-commonsense#38]
Can I Save this atomic model into h5 file or language model file(like : added_tokens.json,config.json,pytorch_model.bin,vocab.json..)

**Comment by atcbosselut** [comment]
Yes, you'll have to modify the save methods in:

https://github.com/atcbosselut/comet-commonsense/blob/master/src/data/data.py

but it should be possible.
