### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by zysNLP** [atcbosselut/comet-commonsense#8]
Hi, when I execute the training got:

(PyTorch) zys@zys:~/Documents/gits/comet-commonsense$ python src/main.py --experiment_type atomic --experiment_num 0
config/atomic/config_0.json
{'gpu_mode': 'T', 'gpu_index': 0, 'gpu_indices': [0, 1], 'multigpu': 'F', 'topk_size': 10, 'beam_size': 1, 'gen_seqlength': 40, 'eval_sampler': 'greedy', 'num_sequences': 1, 'generate_sequences': 1000, 'evaluate_sequences': 10000, 'random_seed': 123, 'optimizer': 'adam', 'batch_size': 64, 'learning_rate': 6.25e-05, 'clip': 1, 'loss': 'nll', 'weight_decay': 0, 'adam': {'b2': 0.999, 'b1': 0.9, 'e': 1e-08}, 'model': 'transformer', 'pretrain': 'gpt', 'hidden_dim': 768, 'num_layers': 12, 'num_heads': 12, 'embedding_dropout': 0.1, 'attention_dropout': 0.1, 'residual_dropout': 0.1, 'output_dropout': 0.1, 'activation': 'gelu', 'init': 'pt', 'trainer': 'iteration', 'iterations': 50000, 'cycle': 500, 'save_strategy': 'best', 'epochs': 20, 'toy': 'F', 'do_gen': 'F', 'save': 'T', 'test_save': 'F', 'dataset': 'atomic', 'categories': ['oEffect'], 'eval_categories': ['oEffect'], 'exp': 'generation', 'labels': 'individual', 'encoder_path': 'model/encoder_bpe_40000.json', 'bpe_path': 'model/vocab_40000.bpe', 'learning_rate_schedule': 'warmup_linear', 'learning_rate_warmup': 0.002, 'l2': 0.01, 'vector_l2': 'T'}
{'b2': 0.999, 'b1': 0.9, 'e': 1e-08}
DD{'net': DD{'model': 'transformer', 'nL': 12, 'nH': 12, 'hSize': 768, 'edpt': 0.1, 'adpt': 0.1, 'rdpt': 0.1, 'odpt': 0.1, 'pt': 'gpt', 'afn': 'gelu', 'init': 'pt'}, 'mle': 0, 'dataset': 'atomic', 'train': DD{'static': DD{'exp': 'generation', 'seed': 123, 'l2': 0.01, 'vl2': True, 'lrsched': 'warmup_linear', 'lrwarm': 0.002, 'clip': 1, 'loss': 'nll', 'b2': 0.999, 'b1': 0.9, 'e': 1e-08}, 'dynamic': DD{'lr': 6.25e-05, 'bs': 64, 'optim': 'adam'}}, 'model': 'transformer', 'exp': 'generation', 'data': DD{'categories': ['oEffect'], 'maxe1': 17, 'maxe2': 35, 'maxr': 1}, 'eval': DD{'bs': 1, 'smax': 40, 'sample': 'greedy', 'numseq': 1, 'gs': 1000, 'es': 10000, 'categories': ['oEffect']}, 'trainer': 'iteration', 'cycle': 500, 'iters': 50000}
Loading Data
Loading data from: data/atomic/processed/generation/categories_oEffect-maxe1_17-maxe2_35-maxr_1.pickle
61795
Done.
dict_keys(['data', 'sequences', 'masks', 'offsets', 'categories', 'opt', 'vocab_encoder', 'vocab_decoder', 'special_chars', 'max_event', 'max_effect', 'batch_size'])
Building Model
50
LOADING PRETRAINED TRANSFORMER
Loading weights...
Done.
Files will be logged at: results/losses/atomic-generation/iteration-500-50000/transformer/categories_oEffect-maxe1_17-maxe2_33-maxr_1/model_transformer-nL_12-nH_12-hSize_768-edpt_0.1-adpt_0.1-rdpt_0.1-odpt_0.1-pt_gpt-afn_gelu-init_pt-vSize_40532/exp_generation-seed_123-l2_0.01-vl2_T-lrsched_warmup_linear-lrwarm_0.002-clip_1-loss_nll-b2_0.999-b1_0.9-e_1e-08/bs_1-smax_40-sample_greedy-numseq_1-gs_1000-es_10000-categories_oEffect/6.25e-05_adam_64_0
Pushing to GPU: 0
Done.
Training
Logging Tensorboard Files at: logs/atomic-generation/iteration-500-50000/transformer/categories_oEffect-maxe1_17-maxe2_33-maxr_1/model_transformer-nL_12-nH_12-hSize_768-edpt_0.1-adpt_0.1-rdpt_0.1-odpt_0.1-pt_gpt-afn_gelu-init_pt-vSize_40532/exp_generation-seed_123-l2_0.01-vl2_T-lrsched_warmup_linear-lrwarm_0.002-clip_1-loss_nll-b2_0.999-b1_0.9-e_1e-08/bs_1-smax_40-sample_greedy-numseq_1-gs_1000-es_10000-categories_oEffect/6.25e-05_adam_64
  0%|                                                 | 0/50000 [00:00<?, ?it/s]{'total_micro': [0], 'total_macro': [0], 'oEffect_micro': [0], 'oEffect_macro': [0]}
  0%|                                      | 1/50000 [00:00<10:46:40,  1.29it/s]Traceback (most recent call last):
  File "src/main.py", line 16, in <module>
    main(args.experiment_num)
  File "/home/zys/Documents/gits/comet-commonsense/src/main_atomic.py", line 125, in main
    trainer.run()
  File "/home/zys/Documents/gits/comet-commonsense/src/train/train.py", line 194, in run
    self.cycle(bar, cycle_num)
  File "/home/zys/Documents/gits/comet-commonsense/src/train/train.py", line 212, in cycle
    loss, nums, reset = self.do_forward_pass(nums)
  File "/home/zys/Documents/gits/comet-commonsense/src/train/train.py", line 159, in do_forward_pass
    self.batch_variables)
  File "/home/zys/Documents/gits/comet-commonsense/src/train/atomic_train.py", line 34, in batch
    outputs = batch.batch_atomic_generate(opt, *args)
  File "/home/zys/Documents/gits/comet-commonsense/src/train/batch.py", line 37, in batch_atomic_generate
    attention_mask[:, :-1], loss_reduction="none")
  File "/home/zys/Documents/gits/comet-commonsense/src/train/batch.py", line 108, in mle_steps
    attention_mask, i)
  File "/home/zys/Documents/gits/comet-commonsense/src/train/batch.py", line 125, in decode
    return model(input_, sequence_mask=attention_mask)
  File "/home/zys/anaconda3/envs/PyTorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zys/Documents/gits/comet-commonsense/src/models/gpt.py", line 212, in forward
    lm_logits = lm_logits + self.pos_emb_mask
RuntimeError: CUDA out of memory. Tried to allocate 486.00 MiB (GPU 0; 7.76 GiB total capacity; 6.32 GiB already allocated; 48.56 MiB free; 437.98 MiB cached)
  0%|                                      | 1/50000 [00:00<13:40:12,  1.02it/s]

Could you tell me your minimum configuration of GPU? I use a NVIDIA2060 got these errors.

**Comment by atcbosselut** [comment]
I think NVIDIA2060s have around 6GB of GPU memory. Our default configuration is for a Titan Xp with 12 GB. I'd reduce the batch size to 32 and see if that works. If you're still running out of memory, reduce it further.
